
package projeto.telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Gerando Falcoes
 */
public class TelaMenuAtendente extends javax.swing.JFrame {

    /**
     * Creates new form VisaoAtendente
     */
    public TelaMenuAtendente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pedidosMenuAdminButton = new javax.swing.JButton();
        usuariosMenuAtendenteButton = new javax.swing.JButton();
        produtosMenuAtendenteButton = new javax.swing.JButton();
        editarMaquinaMenuAtendenteButton = new javax.swing.JButton();
        visualizarCardapioMenuAtendenteButton = new javax.swing.JButton();
        voltarMenuAdminButton = new javax.swing.JButton();
        sairMenuAdminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pedidosMenuAdminButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pedidosMenuAdminButton.setText("Pedidos");
        pedidosMenuAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosMenuAdminButtonActionPerformed(evt);
            }
        });

        usuariosMenuAtendenteButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usuariosMenuAtendenteButton.setText("Usuários");
        usuariosMenuAtendenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosMenuAtendenteButtonActionPerformed(evt);
            }
        });

        produtosMenuAtendenteButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtosMenuAtendenteButton.setText("Produtos");
        produtosMenuAtendenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosMenuAtendenteButtonActionPerformed(evt);
            }
        });

        editarMaquinaMenuAtendenteButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        editarMaquinaMenuAtendenteButton.setText("Editar Máquina");
        editarMaquinaMenuAtendenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMaquinaMenuAtendenteButtonActionPerformed(evt);
            }
        });

        visualizarCardapioMenuAtendenteButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        visualizarCardapioMenuAtendenteButton.setText("Visualizar Cardápio");
        visualizarCardapioMenuAtendenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarCardapioMenuAtendenteButtonActionPerformed(evt);
            }
        });

        voltarMenuAdminButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        voltarMenuAdminButton.setText("Voltar");
        voltarMenuAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuAdminButtonActionPerformed(evt);
            }
        });

        sairMenuAdminButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sairMenuAdminButton.setText("Sair");
        sairMenuAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(voltarMenuAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sairMenuAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pedidosMenuAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(produtosMenuAtendenteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editarMaquinaMenuAtendenteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usuariosMenuAtendenteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(visualizarCardapioMenuAtendenteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pedidosMenuAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(usuariosMenuAtendenteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(editarMaquinaMenuAtendenteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(produtosMenuAtendenteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(visualizarCardapioMenuAtendenteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(voltarMenuAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(sairMenuAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuariosMenuAtendenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosMenuAtendenteButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Voce nao possui acesso a esta funcionalidade");
    }//GEN-LAST:event_usuariosMenuAtendenteButtonActionPerformed

    private void voltarMenuAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuAdminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarMenuAdminButtonActionPerformed

    private void sairMenuAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuAdminButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairMenuAdminButtonActionPerformed

    private void pedidosMenuAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosMenuAdminButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Voce nao possui acesso a esta funcionalidade");
    }//GEN-LAST:event_pedidosMenuAdminButtonActionPerformed

    private void produtosMenuAtendenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosMenuAtendenteButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Voce nao possui acesso a esta funcionalidade");
    }//GEN-LAST:event_produtosMenuAtendenteButtonActionPerformed

    private void editarMaquinaMenuAtendenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMaquinaMenuAtendenteButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Voce nao possui acesso a esta funcionalidade");
    }//GEN-LAST:event_editarMaquinaMenuAtendenteButtonActionPerformed

    private void visualizarCardapioMenuAtendenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarCardapioMenuAtendenteButtonActionPerformed
        TelaVisualizarCardapio tvc = new TelaVisualizarCardapio();
        tvc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_visualizarCardapioMenuAtendenteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarMaquinaMenuAtendenteButton;
    private javax.swing.JButton pedidosMenuAdminButton;
    private javax.swing.JButton produtosMenuAtendenteButton;
    private javax.swing.JButton sairMenuAdminButton;
    private javax.swing.JButton usuariosMenuAtendenteButton;
    private javax.swing.JButton visualizarCardapioMenuAtendenteButton;
    private javax.swing.JButton voltarMenuAdminButton;
    // End of variables declaration//GEN-END:variables
}
